### ISSUE TITLE
Failed to compile the BPD module with errors under both Pytorch1.2 & Pytorch1.5

### ISSUE THREAD

**Issue by PkuRainBow** [JianqiangWan/Super-BPD#2]
Hi, Really nice work!

We have tried to compile the BPD module in the post_process folder and got different error information based on Pytorch1.2 or Pytorch1.5 as below.

- Pytorch1.2 errors:

![image](https://user-images.githubusercontent.com/4639578/83417569-d9698200-a454-11ea-975d-b89194f81774.png)

- Pytorch1.5 errors:
![image](https://user-images.githubusercontent.com/4639578/83417628-f30ac980-a454-11ea-88e4-064c2ca7f3a1.png)

Thanks!

**Comment by JianqiangWan** [comment]
please use pytorch=1.3.0 or 1.4.0 for the time being.

**Comment by JianqiangWan** [comment]
Please use pytorch >= 1.3.0.
For pytorch = 1.5.0, it looks like a compatibility issue with gcc and nvcc , upgraded to gcc 7 and the compilation passed without a problem. ref. https://github.com/rusty1s/pytorch_geometric/issues/942.
