### ISSUE TITLE
How to test a single RGB image? 

### ISSUE THREAD

**Issue by carfei** [JianqiangWan/Super-BPD#4]
Thank you very much for your work. If I want to test an RGB image, can I get a semantic segmentation graph through the model input picture, and I want clear visualization results, can I get a more precise semantic segmentation graph?

**Comment by JianqiangWan** [comment]
1. Compile and install the post_process program.
2. Transform input image to a two channel direction map (pred_flux), refer to `test.py`.
3. https://github.com/JianqiangWan/Super-BPD/blob/3c44638117625001ea0a92616f339c6ae4d5b956/post_process/demo.py#L34-L42
4. The final segmentation result has no semantic information，and post-processing includes the construction and connection process of the Region Adjacency Graph (RAG), we didn't output the RAG.
